name: Macrograd

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure and build
      run: |
        mkdir build
        cmake -S . -B build
        cmake --build build

    - name: Run tests
      run: |
        cd build/tests
        ctest --output-on-failure

  manual_trigger:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Manual trigger
      uses: actions/github-script@v4
      with:
        script: |
          const output = await github.actions.createWorkflowDispatch({
            workflow_id: '${{ github.workflow }}',
            ref: '${{ github.sha }}'
          })
          console.log(output)